### ISSUE TITLE
Improve Spellcheck

### ISSUE THREAD

**Issue by cuminandpaprika** [anz-bank/sysl-website#50]
Currently the developer experience for adding words to the spellcheck is quite tedious.

Many of the words used in fenced code blocks using both `` single backticks and triple backticks are not properly ignored.

```bash
something
```

## Attempted Solutions

I've tried using the following config but it fails to filter out fenced code blocks. Perhaps we need to put in a PR downstream to https://github.com/facelessuser/pyspelling

```yaml
    pipeline:
      - pyspelling.filters.markdown:
        markdown_extensions:
          - markdown.extensions.fenced_code
```
