### ISSUE TITLE
Set proxy for downstream

### ISSUE THREAD

**Issue by ericzhang6222** [anz-bank/sysl-website#81]
In page https://sysl.io/docs/tutorial-codegen/, it can't access downstream sometimes without proxy, and there is not any document say how to set proxy.
Set proxy for downstream:
```
  downstream:
    contextTimeout: 120s
    petstore:
      serviceURL: ${URL}
      clientTimeout: 59s
      clientTransport:
        useProxy: true
        proxyURL: http://127.0.0.1:1081
```
